### ISSUE TITLE
Feature Request: C64 support

### ISSUE THREAD

**Issue by coleshores** [RevCurtisP/C02#10]
This could be very handy in the C64 homebrew community.  I have been looking for something like this for a while.  Any chance you could upgrade the Vic20 libraries to C64?
Thanks,
Cole

**Comment by RevCurtisP** [comment]
The /vic20/include directory is deprecated. I will rename the directory to prevent confusion. 

All standard library code is in /include. The C64 specific code is up to date and is in /include/c64. 

All programs in /test have been compiled for the C64-and tested. See the file /test/c64.bat for the compiler and assembler command line options.

**Comment by coleshores** [comment]
Thanks for the clarity, Ill run with that /include!

**Comment by RevCurtisP** [comment]
Using <file.
