### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by DarkiStar** [RevCurtisP/C02#6]
The current licence of this great piece of software makes it difficult to contribute to it.

`(C) 2012 Curtis F Kaylor`

Are there any plans to move it to LGPL or MIT licence? If yes I would like to start to write some PRs.

regards

PS.: It compiles fine with actual versions of Visual Studio 2017 Community Edition (for Windows) if a warning is disabled. Better solution are some improvements to the code which will be part of a PR.

**Comment by matozoid** [comment]
@RevCurtisP same here: you really should pick a license.

**Comment by RevCurtisP** [comment]
Project has been licensed under the Mozilla Public License 2.0
